---
title: "#Agents: Sample Statistics 2020" 
output: html_document
---

This is a documentation of the #Agents -data. 

```{r include=F}
knitr::opts_chunk$set(echo = FALSE, fig.width = 10, fig.fullwidth = T)
```


```{r include=F}
library(rmarkdown)
library(knitr)
library(tidyverse)
library(magrittr)
library(gridExtra)
library(openxlsx)
```


```{r}
data <- read.xlsx("13110 Jyväskylän yliopisto Nuorisotutkimus DATA.xlsx", sheet=1, colNames=T)
data %<>% dplyr::rename(occu=q14, schl=q16, habi=q18, sex=q11, age=q12, medu=q17, ffina=q290, ofina=q291) 
```


```{r include=F}
theme_set(theme_classic()) + 
theme_update(axis.text.x = element_text(size = 12),
             legend.title = element_blank(),
             plot.title = element_text(hjust = 0.5, size =16))
```

## Missing values (from SPSS)
  see: Syntax1_MVA.sps; Output1_MVA.spv

```{r include=F}
MVA <- matrix(c(162,.12),ncol=2, nrow=1)
colnames(MVA) <- c("f","%")
rownames(MVA) <- c("Missing Values")
MVA <- as.table(MVA)
```


```{r}
kable(MVA, digits = c(0,2), align = c('c','c'))
```


```{r include=F}
MCAR <- matrix(c(4196.685, 4179, .421), ncol=3, nrow=1)
colnames(MCAR) <- c("chisq", "df", "p")
rownames(MCAR) <- ("Little's MCAR test")
MCAR <- as.table (MCAR)
```


```{r}
kable(MCAR, digits = c(2, 0, 3), align = c('c','c','c'))
```


```{r include = F}
data %<>% 
  mutate(occu=factor(occu, labels = c("Studying", "Working", "Army/civil service", "Other"))) %>%
  mutate(schl=replace_na(schl, "0")) %>%
  mutate(schl=factor(schl, labels = c("Not studying","Comprehensive school","High school","Vocational School",
                                      "High school + vocational","Applied University","University"))) %>%
  mutate(habi=factor(habi, labels = c("Partner", "Parents", "Independently", "Other"))) %>%
  mutate(sex=factor(sex, labels = c("Male","Female"))) %>%
  mutate(medu=ordered(medu, labels = c("Comprehensive School", "High School", "Vocational School",
                                       "Vocational College",  "Applied University", "University", "Unknown"))) %>%
  mutate(ffina=ordered(ffina, labels = c("Very Poor", "Poor", "Adequate", "Good", "Very Good"))) %>%
  mutate(ofina=ordered(ofina, labels = c("Very Poor", "Poor", "Adequate", "Good", "Very Good")))
```

## Gender and Age

```{r include = F}
saf <- table(data$sex, data$age)
sap <- prop.table(saf)
sap <- sap*100
Sex_Age <- as.data.frame(rbind(saf, sap))
Sex_Age <- Sex_Age[c(1,3,2,4),]
Sex_Age$Sex <- c("Male", "", "Female", "")
Sex_Age$Value <- c("freq","%","freq","%")
rownames(Sex_Age) <- seq(1:4)
Sex_Age <- Sex_Age[, c(6,7,1:5)]
colnames(Sex_Age)[3:7] <- c("15 Years", "16 Years", "17 Years", "18 Years", "19 Years")
```


```{r}
kable(Sex_Age, digits = 0, align = c('l', 'c', 'c', 'c', 'c', 'c', 'c'), Caption = "Age and Gender distribution")
```

## Current status

```{r include=F}
ol1 <- data %>% drop_na(occu) %>% ggplot(aes(x = occu, fill=occu)) +
  geom_bar(stat="count", color="black") + 
  scale_fill_brewer(palette="BuGn") +
  labs(title="Current status", x = "", y = "Count") +
  theme(axis.text.x = element_blank(),
        axis.ticks = element_blank())

ol2 <- data %>% drop_na(schl) %>% ggplot(aes(x = schl, fill=schl)) + 
  geom_bar(stat="count", color="black") +
  scale_fill_brewer(palette="BuGn") +
  labs(title="School level", x = "", y = "Count") +
  theme(axis.text.x = element_blank(),
        axis.ticks = element_blank())

ol3 <- data %>% drop_na(habi) %>% ggplot(aes(x = habi, fill=habi)) + 
  geom_bar(stat="count", color="black") + 
  scale_fill_brewer(palette="BuGn") +
  labs(title="Living arrangement", x = "", y = "Count") +
  theme(axis.text.x = element_blank(),
        axis.ticks = element_blank())

p <- list(ol1, ol2, ol3)

```


```{r}
grid.arrange(grobs = p, widths = c(1, 1), layout_matrix = rbind(c(1, 3),
                                                                c(2, 2)))
```


```{r include=F}
of <- table(data$schl, data$occu)
op <- prop.table(of)
op <- op*100
Occupation <- as.data.frame(rbind(of, op))
Occupation <-  Occupation[c(1,8,2,9,3,10,4,11,5,12,6,13,7,14),] 
Occupation$Level <- c("Not studying", "", "Comprehensive school", "", "High school", "", "Vocational school",
                      "", "High school + vocational", "", "Applied college", "", "University", "")
Occupation$Value <- c("freq","%","freq","%","freq","%","freq","%","freq","%","freq","%","freq","%")
rownames(Occupation) <- seq(1:14)
Occupation <- Occupation[, c(5,6,1:4)]
```


```{r}
kable(Occupation, digits=0, caption = "Educational level (or occupational status)", align = c('l','c','c','c','c','c'))
```


```{r include=F}
hf <- table(data$habi)
hp <- prop.table(hf)
hp <- hp*100
Living <- as.data.frame(rbind(hf, hp))
rownames(Living) <- c("freq", "%")
```


```{r}
kable(Living, digits = 0, caption = "Living with", align = c('c','c','c','c'))
```

# Socio-economic status

```{r include=F}
data %<>%  mutate(ses1 = recode(medu, "Comprehensive School"=1, "High School"=2, "Vocational School"=2,
                     "Vocational College"=3, "Applied University"=3, "University"=4,
                     "Unknown"= NA_real_)) %>%
         mutate(ses2 = recode(ffina, "Very Poor"=1, "Poor"=1, "Adequate"=2, "Good"=3, "Very Good"=4)) %>%
         mutate(ses3 = recode(ofina, "Very Poor"=1, "Poor"=1, "Adequate"=2, "Good"=3, "Very Good"=4)) %>%
         mutate(ses = rowMeans(select(., c(ses1:ses3)), na.rm = T))
```

```{r include=F}
p1 <- data %>% drop_na(medu) %>% ggplot(aes(x = medu, fill=medu)) +
  geom_bar(stat="count", color="black") + 
  scale_fill_brewer(palette="PuBuGn") +
  labs(title="Mother's education", x = "", y = "Count") +
  theme(axis.text.x = element_blank(),
        axis.ticks = element_blank())

p2 <- data %>% drop_na(ffina) %>% ggplot(aes(x = ffina, fill=ffina)) + 
  geom_bar(stat="count", color="black") +
  scale_fill_brewer(palette="PuBuGn") +
  labs(title="Family financial situation", x = "", y = "Count") +
  theme(axis.text.x = element_blank(),
        axis.ticks = element_blank())

p3 <- data %>% drop_na(ofina) %>% ggplot(aes(x = ofina, fill=ofina)) + 
  geom_bar(stat="count", color="black") + 
  scale_fill_brewer(palette="PuBuGn") +
  labs(title="Personal financial situation", x = "", y = "Count") +
  theme(axis.text.x = element_blank(),
        axis.ticks = element_blank())

p4 <- data %>% ggplot(aes(x = ses, fill=..count..)) + 
  geom_histogram(color="black", binwidth=.25) + 
  scale_color_gradientn(colours = rainbow(5)) +
  labs(title="Socio-economic status (SES) index", x = "", y = "Count")

p <- list(p1, p2, p3, p4)

```


```{r}
grid.arrange(grobs = p, widths = c(1, 1, 1), layout_matrix = rbind(c(1, 1, 4),
                                                                   c(2, 3, 4)))
```

```{r include=F}
mf <- table(data$medu)
mp <- prop.table(mf)
mp <- mp*100
Mom_Edu <- as.data.frame(rbind(mf, mp))
rownames(Mom_Edu) <- c("freq", "%")
```


```{r}
kable(Mom_Edu, digits=c(0), caption = "Mother's educational level", align = c('c','c','c','c','c','c','c'))
```


```{r include=F}
ff <- table(data$ffina)
fp <- prop.table(ff)
fp <- fp*100
of <- table(data$ofina)
op <- prop.table(of)
op <- op*100
Fin.sit <- as.data.frame(rbind(ff, fp, of, op))
Fin.sit$Value <- c("freq", "%", "freq", "%")
Fin.sit$Variable <- c("Family", "", "Personal", "")
rownames(Fin.sit) <- seq(1:4)
Fin.sit <- Fin.sit[, c(7,6,1:5)]
```


```{r}
kable(Fin.sit, digits = 0, caption = "Financial situation", align = c('l', 'c','c','c','c','c','c'))
```



